import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { Providers } from "@/app/providers";
import { SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Milvus Next Example",
  description: "Generated by create next app",
};

const DEFAULT_REFERRER = "http://localhost:3000";

const Html = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = await headers();
  const referer = header.get("referer");
  const pathname = new URL(referer ?? DEFAULT_REFERRER).pathname;
  const isConnect = pathname === "/connect";

  if (isConnect) {
    return (
      <Html>
        <Providers>{children}</Providers>
      </Html>
    );
  }

  return (
    <Html>
      <Providers>
        <AppSidebar />
        <main>
          <SidebarTrigger />
          {children}
        </main>
      </Providers>
    </Html>
  );
}
